[package]
name = "rufus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitint = "0.1.1"
bytemuck = "1.14.1"
num-derive = "0.4.2"
num-traits = "0.2.18"
